import { notFound } from "next/navigation"
import { supabaseAdmin } from "@/lib/supabase"
import PrintButton from "@/components/mentorship/PrintButton"

export const revalidate = 0
export const metadata = { title: "Mentorship Certificate | Tee's House" }

// Looked up by the unguessable certificate_token — the pair's actual UUID
// is never exposed in this URL. No login required to view/print (a login
// wall would add friction to a one-time share/print link), but the token
// itself is unguessable and can be regenerated by an admin if ever leaked.
export default async function CertificatePage({ params }: { params: { token: string } }) {
  const { data: pair } = await supabaseAdmin
    .from("mentorship_pairs")
    .select(`
      id, session_count, certificate_issued_at, started_at, ended_at,
      mentor:mentors(first_name, last_name),
      mentee:mentorship_applications(first_name, last_name),
      cohort:mentorship_cohorts(name)
    `)
    .eq("certificate_token", params.token)
    .maybeSingle()

  if (!pair || !pair.certificate_issued_at) notFound()

  const mentor = Array.isArray(pair.mentor) ? pair.mentor[0] : pair.mentor
  const mentee = Array.isArray(pair.mentee) ? pair.mentee[0] : pair.mentee
  const cohort = Array.isArray(pair.cohort) ? pair.cohort[0] : pair.cohort

  const { count: goalsCompleted } = await supabaseAdmin
    .from("mentorship_goals")
    .select("*", { count: "exact", head: true })
    .eq("pair_id", pair.id)
    .eq("status", "completed")

  const completionDate = pair.ended_at
    ? new Date(pair.ended_at).toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })
    : ""

  return (
    <>
      <style>{`
        @media print {
          @page { size: landscape; margin: 0; }
          .no-print { display: none !important; }
          body { margin: 0; }
        }
      `}</style>
      <main style={{ minHeight: "100vh", background: "#EAF2E3", display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", padding: "40px 16px" }}>
        <div style={{
          maxWidth: 800, width: "100%", background: "#FBF6EF", border: "10px double #C8860A",
          borderRadius: 12, padding: "56px 48px", textAlign: "center", boxShadow: "0 8px 30px rgba(45,80,22,0.15)",
        }}>
          <div style={{ fontFamily: "Georgia, serif", fontSize: 13, letterSpacing: "0.2em", textTransform: "uppercase", color: "#C8860A", marginBottom: 12 }}>
            Tee&rsquo;s House Inc. &middot; Mentorship Program
          </div>
          <h1 style={{ fontFamily: "Georgia, serif", fontSize: 34, color: "#2D5016", margin: "0 0 24px" }}>
            Certificate of Completion
          </h1>
          <p style={{ fontSize: 16, color: "#6B7280", margin: "0 0 8px" }}>This certifies that</p>
          <div style={{ fontFamily: "Georgia, serif", fontSize: 30, color: "#2D5016", margin: "0 0 16px", fontStyle: "italic" }}>
            {mentee?.first_name} {mentee?.last_name}
          </div>
          <p style={{ fontSize: 16, color: "#444444", maxWidth: 520, margin: "0 auto 28px", lineHeight: 1.6 }}>
            has successfully completed the Tee&rsquo;s House mentorship program
            {cohort?.name ? ` as part of the ${cohort.name} cohort` : ""}, mentored by{" "}
            <strong>{mentor?.first_name} {mentor?.last_name}</strong>.
          </p>
          <div style={{ display: "flex", justifyContent: "center", gap: 48, margin: "0 0 28px" }}>
            <div>
              <div style={{ fontSize: 22, fontWeight: 700, color: "#2D5016" }}>{pair.session_count}</div>
              <div style={{ fontSize: 11, textTransform: "uppercase", letterSpacing: "0.06em", color: "#6B7280" }}>Sessions</div>
            </div>
            <div>
              <div style={{ fontSize: 22, fontWeight: 700, color: "#2D5016" }}>{goalsCompleted ?? 0}</div>
              <div style={{ fontSize: 11, textTransform: "uppercase", letterSpacing: "0.06em", color: "#6B7280" }}>Goals Completed</div>
            </div>
          </div>
          {completionDate && (
            <p style={{ fontSize: 13, color: "#6B7280", margin: 0 }}>Completed {completionDate}</p>
          )}
        </div>
        <PrintButton />
      </main>
    </>
  )
}
